name: Continuous deployment

on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
            wasm-runner/dist
          key: ${{ runner.os }}-cargo

      - name: Install dependencies
        run: |
          cargo install --locked trunk || true \
          && rustup target add wasm32-unknown-unknown

      - name: Build the Rust WASM app and all of its assets
        run: |
          trunk build \
            --release \
            --public-url ${{ github.event.repository.name }} \
            -- \
            ./wasm-runner/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './wasm-runner/dist'

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
